import type { RuntimeEvent } from '../runtime/types'

/**
 * Compatibility fingerprint for the public Core operation registry.
 *
 * The operation names remain owned by `api/operations.ts`; this digest makes an
 * accidental rename, addition, or removal fail loudly at the public boundary.
 */
export const CORE_OPERATION_COMPATIBILITY = Object.freeze({
  count: 154,
  sha256: '3ead1412425cbcd73f46314f13e6a1c6a7c0cf18e06ae27b0ab878540cecce74',
})

/** External runtime event names consumed by the desktop projection. */
export const RUNTIME_EVENT_NAMES = [
  'agent_thought',
  'ask_answered',
  'ask_request',
  'assistant_done',
  'context_projection',
  'context_usage',
  'control_mode_update',
  'environment_changed',
  'environment_install_completed',
  'environment_install_failed',
  'environment_install_progress',
  'environment_install_started',
  'error',
  'git_operation_completed',
  'goal_blocked',
  'goal_cancelled',
  'goal_completed',
  'goal_created',
  'goal_evidence_recorded',
  'goal_gate_evaluated',
  'goal_paused',
  'goal_policy_stopped',
  'goal_resumed',
  'goal_runtime_update',
  'hook_decision_applied',
  'hook_run_completed',
  'hook_run_failed',
  'hook_run_progress',
  'hook_run_started',
  'interaction_cancelled',
  'mcp_connection_state',
  'message_delta',
  'message_tombstoned',
  'model_attempt_cancelled',
  'model_attempt_failed',
  'model_attempt_started',
  'model_attempt_succeeded',
  'model_provider_retry',
  'model_route_fallback',
  'plan_approved',
  'plan_comment_added',
  'plan_draft',
  'plan_draft_delta',
  'plan_entry_decision',
  'plan_execution_settled',
  'plan_runtime_update',
  'plan_step_update',
  'plan_verification_done',
  'plan_verification_start',
  'process_containment',
  'profile_onboarding_status_changed',
  'prompt_cancelled',
  'prompt_dequeued',
  'prompt_interjected',
  'prompt_queued',
  'ready',
  'record_degraded',
  'runtime_task_cancelled',
  'scheduler_job_update',
  'scheduler_run_cancelled',
  'scheduler_run_done',
  'scheduler_run_error',
  'scheduler_run_interrupted',
  'scheduler_run_skipped',
  'scheduler_run_start',
  'session_created',
  'session_title_updated',
  'subagent_delta',
  'subagent_done',
  'subagent_error',
  'subagent_start',
  'subagent_tool_call',
  'subagent_tool_error',
  'subagent_tool_result',
  'task_cancelled',
  'task_done',
  'task_error',
  'task_output',
  'task_progress',
  'task_started',
  'team_member_update',
  'team_message',
  'team_run_delta',
  'team_run_done',
  'team_run_error',
  'team_run_start',
  'team_run_tool_call',
  'team_run_tool_error',
  'team_run_tool_result',
  'tool_call',
  'tool_error',
  'tool_result',
  'tool_run_cancelled',
  'tool_run_completed',
  'tool_run_failed',
  'tool_run_queued',
  'tool_run_started',
  'turn_change_snapshot',
  'turn_paused',
  'turn_phase',
  'turn_scope',
  'user_message',
] as const satisfies readonly RuntimeEvent['event'][]

export const RUNTIME_EVENT_COMPATIBILITY = Object.freeze({
  count: 102,
  sha256: '2539b5358945cc54492877932ae4c43029ea155565bf4723005d0d5cea2ded6a',
})
